@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}


# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "password": "password123"
}
###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "password123"
}
###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "What is the capital of France?",
  "content": "I would like to know the capital city of France."
}
###