services:
  postgres:
    container_name: nest-first
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: nest_user
      POSTGRES_PASSWORD: nest_password
      POSTGRES_DB: nest_first
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres